name: chulla_cash
description: "The only app that gets your money into shape Manage money on the go in the app"
publish_to: 'Playstore and Appstore'
version: 0.1.0+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  #splash screen
  flutter_native_splash: ^2.4.0
  #firebasecore
  firebase_core: ^2.24.2
  #firebase auth
  firebase_auth: ^4.16.0
  #firebase storage
  firebase_storage: ^11.2.0
  #firebase firestore
  cloud_firestore: ^4.13.6
  #getX
  get: ^4.6.5
  #idioma
  intl: 0.19.0
  #flutter localizations
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  #google sign in
  google_sign_in: ^6.2.1
  #apple sign in
  sign_in_with_apple: ^6.1.4
  fl_chart: ^0.65.0
  #image picker
  image_picker: ^1.1.2
  #local auth
  local_auth: ^2.1.7
  url_launcher: ^6.2.4
  #lottie
  lottie: ^3.3.1
  #percent indicator
  percent_indicator: ^4.2.4
  #confetti
  confetti: ^0.8.0
  #audioplayers
  audioplayers: ^6.1.2
  #connectivity
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #icons
  flutter_launcher_icons: ^0.14.2


#icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/icon.jpg"
  min_sdk_android: 21

#splash screen
flutter_native_splash:
  image: lib/assets/icons/icon.jpg
  color: "#FFFFFF"
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/icons/icon_removebg.png
    #img login
    - lib/assets/icons/others/apple.png
    - lib/assets/icons/others/googleIcon.png
    #animations
    - lib/assets/animations/
    #sounds
    - assets/sounds/success.mp3
